spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5433/orders_db
    username: orders_user
    password: orders_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5

    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
        spring.json.trusted.packages: com.learning.order_service.event

      listener:
        ack-mode: manual
        concurrency: 3

server:
  port: 8080

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level [%X{orderReference}] %logger{36} - %msg%n"